### PR TITLE
#231 Integrate State Diagram that is Migrated to JavaFX

### PR DESCRIPTION
**Pull request by kkutschera**
- Created State Diagram 2 which is a version of State Diagram that has been completely migrated to JavaFX which includes all its graphics
- Since self-edges in the state diagram are `Arc` objects rather than an arc in a path, `contains(Point)` has been overridden in `StateTransitionEdgeView2` to account for this

Note that:
- `ArcTo` which is a `PathElement` in JavaFX was not used as it uses a different set of arguments and flags to compute the arc than `GraphicsContext`
- `StateDiagramGraph2*` are direct copies of `StateDiagramGraph*`

### CODE REVIEW

**Comment by prmr** [comment]
I get an NPE:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at ca.mcgill.cs.jetuml.views.edges.StateTransitionEdgeView.getPosition(StateTransitionEdgeView.java:282)
	at ca.mcgill.cs.jetuml.views.edges.StateTransitionEdgeView.getSelfEdgeShape(StateTransitionEdgeView.java:259)
	at ca.mcgill.cs.jetuml.views.edges.StateTransitionEdgeView.getShape(StateTransitionEdgeView.java:244)
	at ca.mcgill.cs.jetuml.views.edges.AbstractEdgeView.getBounds(AbstractEdgeView.java:83)
	at ca.mcgill.cs.jetuml.views.edges.StateTransitionEdgeView.getBounds(StateTransitionEdgeView.java:353)
	at ca.mcgill.cs.jetuml.gui.GraphPanel2$GraphPanelMouseListener.mouseDragged(GraphPanel2.java:908)
	at ca.mcgill.cs.jetuml.gui.GraphPanel2$GraphPanelMouseListener.handle(GraphPanel2.java:957)
	at ca.mcgill.cs.jetuml.gui.GraphPanel2$GraphPanelMouseListener.handle(GraphPanel2.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by kkutschera** [comment]
Additional Changes:
- `WelcomeTab` font size reduced
- Resolved `GraphPanel2` boundary issues
	- Added black border on bottom and right edges of the drawing area for users to distinguish the boundaries of the drawing area
	- Added logic to prevent drawing/moving nodes outside the drawing area
- Zooming has been removed as the current paradigm doesn’t work well with the bounded nature of `GraphPanel2`
- Error message appears if user attempts to zoom on migrated diagrams. Zooming options will be fully removed from the menu once all diagrams are migrated
- Fixed bug with the context menu: now the menu appears where clicked even if scrolled to a different section of the drawing area

**Comment by kkutschera** [comment]
Due to issues noted in #238, the scrollbars have been removed from the drawing area. 
Note that: 
- the only resizing is due to main window resizing
- when window is full screen, there is logic in place to prevent drawing off the screen

**Comment by prmr** [comment]
We also need a bit of logic to prevent any part of the graph from going beyond the canvas boundaries. This works perfectly for the left and top boundaries, works strangely approximately for the right boundary (blocked partway, some calculation error?), and there's no check for the bottom boundary.

**Pull request merged**
