### PR TITLE
#279 - Add staggering when pasting

### PR DESCRIPTION
**Pull request by kkutschera**
Adds staggering when subgraphs are pasted multiple times. Subgraphs are re-positioned to (x,x) from (0,0) in increments of GRID_SIZE if subgraph would overlap with existing subgraph.

Notes:
- I originally anticipated only a need to check if there was an existing node at position (x,x) to prevent staggering. Unfortunately that does not suffice. If we copy and paste a subgraph that does not have a node in the top-left corner of the selection (say pasting a subgraph with a node in the top-right corner and in the bottom-left corner of the selection) solely looking to see if there is a node at position (x,x) will result in overlapping on this subgraph. Thus, my algorithm checks to see if the position of the subgraph nodes are the same as nodes currently in the graph. If this is the case, the subgraph nodes are shifted.

- Although there is no noticeable lag in normal use cases of JetUML, when pasting large subgraphs (tens to hundreds of nodes) multiple times does result in a noticeable lag.

Finally, let me know if you have any suggestions on improvements or if you can think of better ways of implementing staggering.

### CODE REVIEW

**Comment by kkutschera** [comment]
To address your comments:
1) I can't think of a good way to use bounds. It is easy to compute the bounds of the pasted elements, but there isn't a good way to compare the bounds of the pasted elements with the elements currently on the screen. Noting that the bounds of the pasted elements are contained in the bounds of the current elements doesn't provide any useful definitive information. For it to be of any value, we'd need to see if there is a subset of current elements with the same bounds as the bounds of the pasted elements which would be more complex than by doing it using positions. Let me know if you can think of another way to use bounds instead since it would be nicer to use existing methods rather than creating new position methods.
2) I looked into the edge ordering. I didn't find a cause, so I'm not sure if there is an easy way to correct it.
3) I've removed the changes to the Builder class and created a shift method to be used by the paste method.

Question:
Is there a reason we want the subgraphs to be pasted in the corner rather than shifted from its current position? I can double-check, but I think simply removing updatePosition() from copying in the Clipboard would allow pasting shifted from its current position instead of the corner.

**Comment by kkutschera** [comment]
To address your comments:
1) I can't think of a good way to use bounds. It is easy to compute the bounds of the pasted elements, but there isn't a good way to compare the bounds of the pasted elements with the elements currently on the screen. Noting that the bounds of the pasted elements are contained in the bounds of the current elements doesn't provide any useful definitive information. (ex. having two current nodes, one in the top right, another in the bottom left, would result in the current bounds being the entire canvas.) For it to be of any value, we'd need to see if there is a subset of current elements with the same bounds as the bounds of the pasted elements which would be more complex than by doing it using positions. Let me know if you can think of another way to use bounds instead since it would be nicer to use existing methods rather than creating new position methods.
2) I looked into the edge ordering. I didn't find a cause, so I'm not sure if there is an easy way to correct it.
3) I've removed the changes to the Builder class and created a shift method to be used by the paste method.

Question:
Is there a reason we want the subgraphs to be pasted in the corner rather than shifted from its current position? I can double-check, but I think simply removing updatePosition() from copying in the Clipboard would allow pasting shifted from its current position instead of the corner.

**Comment by prmr** [comment]
1. You're right, computing the bounds would require obtaining a `View` object, which is starting to become cumbersome.
2. The issue with the edges is simply that `DiagramView.draw` draws all the nodes, then all the edges. It's interesting that this is only really an issue with pasting. Ultimately we will only be able to solve this once we finally add a Z dimension to the tool. Soon, but not for this PR. So, let's ignore.
3. Great.

Question: No real reason actually. Come to think of it, it might be better.

**Comment by kkutschera** [comment]
- I've added the logic to stagger the pasting from the subgraph's original position
- Additionally, I've ensured that the pasted elements are automatically selected once they are pasted. Before merging this branch I want to look into another way of detecting overlap using the selection bounds

**Comment by kkutschera** [comment]
I've reworked the staggering to use bounds rather than positions. Overall, I think it is better. But, I had to implement a special case for sequence diagrams since the exclusion of activation bars when copying messes with the bounds. So for sequence diagrams I used the condition that the bounds have to be the same _excluding the height_ for it to be overlapped and thus needs to be staggered.

**Comment by kkutschera** [comment]
I definitely agree that having diagram-type dependent logic in the controller is awkward. Moving it to DiagramView is much cleaner

**Pull request merged**
